# Generated by Django 4.2.1 on 2023-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_category1_product_userregister_remove_entry_authors_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category1',
            new_name='Category',
        ),
    ]
