# Generated by Django 4.2.1 on 2023-05-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
