# Generated by Django 4.2.1 on 2023-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_vendorregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendorid',
            field=models.CharField(default='', max_length=150),
        ),
    ]
